### ISSUE TITLE
Gazebo-SITL unable to simulate tracking and flight mission

### ISSUE THREAD

**Issue by glody** [01org/gazebo-sitl#12]
Test Environment
Gazebo-SITL version: c1e07c6
Linux: Ubuntu 14.04 64 Bit Laptop
Purpose:
Check if the tracking and flight mission is able to simulate
Step:
1. Run Ardupilot
2. Run Mavproxy
3. From gzsitl root directory execute the command below
GAZEBO_PLUGIN_PATH=$
{GAZEBO_PLUGIN_PATH}
:$
{PWD}/gzsitl/build GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:${PWD}
/models gazebo ./world/gzsitl_drone_target.world --verbose
4. Press T to enter Translate Mode in Gazebo
5. Drag the sphere to a different position on the grid
6. Run below steps in Mavproxy
param load ..\Tools\autotest\copter_params.parm
mode guided
arm throttle
takeoff 40
wp load ..\Tools\autotest\CMAC-circuit.txt
mode auto
Excepted result:
Gazebo-SITL is able to simulate the tasks
Actual result:
Gazebo-SITL unable to simulate the tasks

git bisect results:
c1e07c6 is the first bad commit
commit c1e07c6932a672bd731f07ccf39a91ee5fc06aa2
Author: Daker Fernandes Pinheiro daker.fernandes.pinheiro@intel.com
Date: Fri Jun 10 15:05:01 2016 -0300
Use guard locker and add {} on switch cases

**Comment by guiccbr** [comment]
Thanks, @glody, pull request #13 fixes it.

**Comment by glody** [comment]
Checked on commit eca6bd3, this issue had fixed.
