### ISSUE TITLE
CMake Error at CMakeLists.txt:16 (install) while making gazebo-sitl

### ISSUE THREAD

**Issue by glody** [01org/gazebo-sitl#16]
Test Environment
Gazebo-SITL version: eca6bd3
Purpose:
Check if the gazebo-sitl is able to build
Step:
1. mkdir ./gzsitl/build
2. cd ./gzsitl/build
3. cmake ..
Excepted result:
Build gazebo-sitl successfully
Actual result:
Error "CMake Error at CMakeLists.txt:16 (install):" shows
Git Bisect Results:
commit 174e6b5871e4c67a52c7bb1d54c3c62cf9592dbd
Author: Anselmo L. S. Melo anselmo.melo@intel.com
Date: Fri Jun 17 17:06:20 2016 -0300
CMake: Move CMakeLists to project's root dir
Log:
/gzsitl/build$ cmake ..
– The C compiler identification is GNU 4.8.4
– The CXX compiler identification is GNU 4.8.4
– Check for working C compiler: /usr/lib/ccache/cc
– Check for working C compiler: /usr/lib/ccache/cc – works
– Detecting C compiler ABI info
– Detecting C compiler ABI info - done
– Detecting C compile features
– Detecting C compile features - done
– Check for working CXX compiler: /usr/lib/ccache/c++
– Check for working CXX compiler: /usr/lib/ccache/c++ – works
– Detecting CXX compiler ABI info
– Detecting CXX compiler ABI info - done
– Detecting CXX compile features
– Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (install):
install TARGETS given no LIBRARY DESTINATION for shared library target
"gzsitl_plugin".
CMake Warning (dev) in CMakeLists.txt:
No cmake_minimum_required command is present. A line of code such as
cmake_minimum_required(VERSION 3.2)
should be added at the top of the file. The version specified may be lower
if you wish to support older CMake versions for this project. For more
information run "cmake --help-policy CMP0000".
This warning is for project developers. Use -Wno-dev to suppress it.
– Configuring incomplete, errors occurred!
See also "/home/drone/Dronecode/Upstream/gazebo-sitl/gzsitl/build/CMakeFiles/CMakeOutput.log".

**Comment by guiccbr** [comment]
Hi, Glody.
The build instructions have been updated on the [README.md](https://github.com/01org/gazebo-sitl/blob/master/README.md).
Also, the gzsitl run command has been updated on the [test plan](https://docs.google.com/a/intel.com/document/d/11f1V86-EcrJlTk7EvfrMfpgVLEEoeECIwqwPmqLlbZE/edit?usp=sharing).

Thanks.

**Comment by glody** [comment]
Verified according the updated README.md
